name: Report a Bug
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in **BetterNether (Forge)**!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Describe the bug in detail.
      value: "A bug happened!"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Versions

  - type: input
    id: bn_version
    attributes:
      label: BetterNether (Forge)
      description: What version of BetterNether (Forge) are you running?
      placeholder: 20.0.*
    validations:
      required: true

  - type: input
    id: bclib_version
    attributes:
      label: BCLib (Forge)
      description: What version of BCLib (Forge) are you running?
      placeholder: 20.0.*
    validations:
      required: true

  - type: input
    id: forge_version
    attributes:
      label: Forge
      description: What version of Forge are you using?
      placeholder: 47.x.x
    validations:
      required: true

  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft
      description: Supported Minecraft version
      options:
        - 1.20.1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (latest.log or crash report).
      render: shell

  - type: textarea
    id: other_mods
    attributes:
      label: Other Mods
      description: Please provide a list of installed mods (besides BetterNether and BCLib).
      render: shell
